version: "3.8"

services:
  mongo-setup:
    container_name: mongo-setup
    image: mongo:latest
    restart: on-failure
    networks:
      default:
    volumes:
      - ./rs-setup:/rs-setup
    entrypoint: ["bash", "/rs-setup/setup.sh"]
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint:
      [
          "/usr/bin/mongod",
          "--bind_ip_all",
          "--replSet",
          "rs0",
          "--journal",
          "--dbpath",
          "/data/db",
          "--enableMajorityReadConcern",
          "false",
      ]
    volumes:
      - ./volumes/mongo/data1/db:/data/db
      - ./volumes/mongo/data1/configdb:/data/configdb
    networks:
      default:

  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27018:27017
    restart: always
    entrypoint:
      [
          "/usr/bin/mongod",
          "--bind_ip_all",
          "--replSet",
          "rs0",
          "--journal",
          "--dbpath",
          "/data/db",
          "--enableMajorityReadConcern",
          "false",
      ]
    volumes:
      - ./volumes/mongo/data2/db:/data/db
      - ./volumes/mongo/data2/configdb:/data/configdb
    networks:
      default:

  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27019:27017
    restart: always
    entrypoint:
      [
          "/usr/bin/mongod",
          "--bind_ip_all",
          "--replSet",
          "rs0",
          "--journal",
          "--dbpath",
          "/data/db",
          "--enableMajorityReadConcern",
          "false",
      ]
    volumes:
      - ./volumes/mongo/data3/db:/data/db
      - ./volumes/mongo/data3/configdb:/data/configdb
    networks:
      default:

  mongo_seed:
    image: mongo:latest
    links:
      - mongo1
    volumes:
      - ./mongo-seed:/mongo-seed
    networks:
      default:
    command:
      bash -c "chmod +x /mongo-seed/restore.sh && /mongo-seed/restore.sh"
    depends_on:
      - mongo-setup

  redis:
    image: redis:5.0.4-alpine
    command: redis-server --requirepass password
    ports:
      - '6379:6379'

  nodejs-application:
    build:
      context: ./ramen-application
    container_name: ramen-application
    image: ramen-application
    env_file:
      - ./ramen-application/.env
    ports:
      - "4000:4000"

  prometheus:
    container_name: prometheus-svc
    image: prom/prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
  grafana:
    image: grafana/grafana:5.0.4
    ports:
      - "3030:3030"
    environment:
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  grafana-dashboards:
    image: alpine:3.10
    depends_on:
      - grafana
    volumes:
      - ./grafana-data:/grafana
    command: >
      /bin/sh -c "
        apk add --no-cache curl
        echo 'waiting for grafana'
        sleep 5s
        cd /grafana
        curl --request POST http://grafana:3000/api/datasources --header 'Content-Type: application/json' -d @datasources.json
        curl --request POST http://grafana:3000/api/dashboards/db --header 'Content-Type: application/json' -d @dashboard.json"

networks:
  default:
    external: false
